#!/usr/bin/env ruby


require 'tta_terms_api'
html = File.expand_path '~/.tta_terms/tta_terms.html'
begin
  search = ARGV.first.downcase
  words_criteria = TtaTermsApi.list search: search
  words = words_criteria.map(&:to_word)
  File.open(html, "w:utf-8") do |f|
    words.each do |word|
      f.puts '<html><head><meta charset="utf-8"></head><body>'
      f.puts "<h1>#{word.name}</h1>" unless word.name.downcase == search
      f.puts "<h1>#{word.origin}</h1>" unless word.origin.downcase == search
      f.puts "<abbr>#{word.type}</abbr>"
      f.puts "<i>#{word.similar}</i>"
      f.puts "<p>#{word.description}</p>"
      f.puts "</body></html>"
    end
  end
rescue
  File.open(html, "w:utf-8") do |f|
    f.puts '<html><head><meta charset="utf-8"></head><body>'
    f.puts "<h1>Not found</h1>"
    f.puts "</body></html>"
  end
end
